-- link: https://leetcode.com/problems/find-the-difference/
--
-- Given two strings s and t which consist of only lowercase letters.
-- String t is generated by random shuffling string s and then add one more letter at a random position.
-- Find the letter that was added in t.

import Data.List

findAdded :: Char -> [Char] -> Bool
findAdded l [] = False
findAdded l p:list 
    | l == p = True
    | otherwise = findAdded l list

-- for some reason, it doesn't compile

lista = "abcd"
listb = "abcde"


