-- link: https://leetcode.com/problems/find-the-difference/		
--		
-- Given two strings s and t which consist of only lowercase letters.		
-- String t is generated by random shuffling string s and then add one more letter at a random position.		
-- Find the letter that was added in t.

findAdded :: Char -> [Char] -> Bool
findAdded letter [] = True
findAdded letter (first:rest)
    | letter == first = False
    | otherwise = findAdded letter rest


-- a is supposed to be the longer list
-- each of its charactesrs will be compared
-- to all characters in b
compareLists :: [Char] -> [Char] -> Maybe Char
compareLists [] b = Nothing
compareLists (a:rest) b
    | findAdded a b = Just a
    | otherwise = compareLists rest b

-- I wonder how should I deal with lists of different sizes.
-- well, it's not explained in the problem so it's not that important I tink.

